version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - custom
    depends_on:
      - db
      - db_test
    command: "sh -c 'alembic upgrade heads && uvicorn main:app --host 0.0.0.0 --port 8000'"
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db -p 5432 -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db -p 5432 -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - custom
networks:
  custom:
    driver: bridge