"""initial migrations v2

Revision ID: 5735dd761a51
Revises: 92202a15b964
Create Date: 2023-10-08 06:02:32.430402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5735dd761a51'
down_revision: Union[str, None] = '92202a15b964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'balances', ['balance_id'])
    op.create_foreign_key(None, 'balances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.drop_constraint(None, 'balances', type_='unique')
    op.drop_column('balances', 'user_id')
    # ### end Alembic commands ###
