"""initial migrations

Revision ID: 92202a15b964
Revises: 
Create Date: 2023-10-08 05:53:59.587479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92202a15b964'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('balances')
    # ### end Alembic commands ###
